/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MarketingHomeRouteImport } from './routes/_marketing/home'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppTribeSelectionRouteImport } from './routes/_app/tribe-selection'
import { Route as AppVillagesIndexRouteImport } from './routes/_app/villages/index'
import { Route as AppVillagesVillageIdRouteImport } from './routes/_app/villages/$villageId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MarketingHomeRoute = MarketingHomeRouteImport.update({
  id: '/_marketing/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTribeSelectionRoute = AppTribeSelectionRouteImport.update({
  id: '/tribe-selection',
  path: '/tribe-selection',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVillagesIndexRoute = AppVillagesIndexRouteImport.update({
  id: '/villages/',
  path: '/villages/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVillagesVillageIdRoute = AppVillagesVillageIdRouteImport.update({
  id: '/villages/$villageId',
  path: '/villages/$villageId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/tribe-selection': typeof AppTribeSelectionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/home': typeof MarketingHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/villages/$villageId': typeof AppVillagesVillageIdRoute
  '/villages': typeof AppVillagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tribe-selection': typeof AppTribeSelectionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/home': typeof MarketingHomeRoute
  '/admin': typeof AdminIndexRoute
  '/villages/$villageId': typeof AppVillagesVillageIdRoute
  '/villages': typeof AppVillagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app/tribe-selection': typeof AppTribeSelectionRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_marketing/home': typeof MarketingHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/villages/$villageId': typeof AppVillagesVillageIdRoute
  '/_app/villages/': typeof AppVillagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/tribe-selection'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/home'
    | '/admin/'
    | '/villages/$villageId'
    | '/villages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tribe-selection'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/home'
    | '/admin'
    | '/villages/$villageId'
    | '/villages'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/admin'
    | '/_app/tribe-selection'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_marketing/home'
    | '/admin/'
    | '/_app/villages/$villageId'
    | '/_app/villages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MarketingHomeRoute: typeof MarketingHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_marketing/home': {
      id: '/_marketing/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MarketingHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/tribe-selection': {
      id: '/_app/tribe-selection'
      path: '/tribe-selection'
      fullPath: '/tribe-selection'
      preLoaderRoute: typeof AppTribeSelectionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/villages/': {
      id: '/_app/villages/'
      path: '/villages'
      fullPath: '/villages'
      preLoaderRoute: typeof AppVillagesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/villages/$villageId': {
      id: '/_app/villages/$villageId'
      path: '/villages/$villageId'
      fullPath: '/villages/$villageId'
      preLoaderRoute: typeof AppVillagesVillageIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppTribeSelectionRoute: typeof AppTribeSelectionRoute
  AppVillagesVillageIdRoute: typeof AppVillagesVillageIdRoute
  AppVillagesIndexRoute: typeof AppVillagesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTribeSelectionRoute: AppTribeSelectionRoute,
  AppVillagesVillageIdRoute: AppVillagesVillageIdRoute,
  AppVillagesIndexRoute: AppVillagesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MarketingHomeRoute: MarketingHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
